package cl.speedfast.ui;
import cl.speedfast.dao.PedidoDAO; import cl.speedfast.model.Pedido;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*;
public class PedidoPanel extends JPanel {
 private final PedidoDAO dao=new PedidoDAO();private final JTextField direccion=new JTextField(22);private final JComboBox<String> tipo=new JComboBox<>(new String[]{"COMIDA","ENCOMIENDA","EXPRESS"}),estado=new JComboBox<>(new String[]{"PENDIENTE","EN_REPARTO","ENTREGADO"});private final JComboBox<String> filtroTipo=new JComboBox<>(new String[]{"Todos","COMIDA","ENCOMIENDA","EXPRESS"}),filtroEstado=new JComboBox<>(new String[]{"Todos","PENDIENTE","EN_REPARTO","ENTREGADO"});private final DefaultTableModel m=UiSupport.model("ID","Dirección","Tipo","Estado");private final JTable t=UiSupport.table(m);
 public PedidoPanel(){setLayout(new BorderLayout(8,8));JPanel top=new JPanel(new GridLayout(3,1));top.add(UiSupport.fields(new JLabel("Dirección:"),direccion,new JLabel("Tipo:"),tipo,new JLabel("Estado:"),estado));JButton save=new JButton("Guardar"),del=new JButton("Eliminar"),clear=new JButton("Limpiar"),refresh=new JButton("Actualizar tabla"),filter=new JButton("Filtrar"),all=new JButton("Quitar filtros");top.add(UiSupport.buttons(save,del,clear,refresh));top.add(UiSupport.fields(new JLabel("Estado:"),filtroEstado,new JLabel("Tipo:"),filtroTipo,filter,all));add(top,BorderLayout.NORTH);add(new JScrollPane(t),BorderLayout.CENTER);save.addActionListener(e->save());del.addActionListener(e->delete());clear.addActionListener(e->{t.clearSelection();direccion.setText("");});refresh.addActionListener(e->load("",""));filter.addActionListener(e->load(filtroEstado.getSelectedIndex()==0?"":filtroEstado.getSelectedItem().toString(),filtroTipo.getSelectedIndex()==0?"":filtroTipo.getSelectedItem().toString()));all.addActionListener(e->{filtroEstado.setSelectedIndex(0);filtroTipo.setSelectedIndex(0);load("","");});t.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&t.getSelectedRow()>=0){int r=t.convertRowIndexToModel(t.getSelectedRow());direccion.setText(m.getValueAt(r,1).toString());tipo.setSelectedItem(m.getValueAt(r,2));estado.setSelectedItem(m.getValueAt(r,3));}});load("","");}
 private int id(){int r=t.getSelectedRow();return r<0?-1:Integer.parseInt(m.getValueAt(t.convertRowIndexToModel(r),0).toString());}
 private void save(){if(!UiSupport.required(direccion.getText())){JOptionPane.showMessageDialog(this,"Ingresa la dirección del pedido.");return;}Pedido p=new Pedido(direccion.getText().trim(),tipo.getSelectedItem().toString(),estado.getSelectedItem().toString());try{if(id()<0){dao.create(p);JOptionPane.showMessageDialog(this,"Pedido registrado.");}else{dao.update(id(),p);JOptionPane.showMessageDialog(this,"Pedido actualizado.");}direccion.setText("");t.clearSelection();load("","");}catch(Exception e){UiSupport.error(this,e);}}
 private void delete(){if(id()<0){JOptionPane.showMessageDialog(this,"Selecciona un pedido.");return;}if(JOptionPane.showConfirmDialog(this,"¿Eliminar pedido seleccionado?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{dao.delete(id());JOptionPane.showMessageDialog(this,"Pedido eliminado.");load("","");}catch(Exception e){UiSupport.error(this,e);}}
 private void load(String est,String tip){try{m.setRowCount(0);for(Pedido p:dao.readAll(est,tip))m.addRow(new Object[]{p.getId(),p.getDireccion(),p.getTipo(),p.getEstado()});}catch(Exception e){UiSupport.error(this,e);}}
}
