package cl.speedfast.ui;
import cl.speedfast.dao.RepartidorDAO; import cl.speedfast.model.Repartidor;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.sql.SQLException;
public class RepartidorPanel extends JPanel {
 private final RepartidorDAO dao=new RepartidorDAO();private final JTextField nombre=new JTextField(24);private final DefaultTableModel m=UiSupport.model("ID","Nombre");private final JTable t=UiSupport.table(m);
 public RepartidorPanel(){setLayout(new BorderLayout(8,8));JPanel top=new JPanel(new BorderLayout());top.add(UiSupport.fields(new JLabel("Nombre:"),nombre),BorderLayout.NORTH);JButton save=new JButton("Guardar"),del=new JButton("Eliminar"),clear=new JButton("Limpiar"),refresh=new JButton("Actualizar tabla");top.add(UiSupport.buttons(save,del,clear,refresh),BorderLayout.SOUTH);add(top,BorderLayout.NORTH);add(new JScrollPane(t),BorderLayout.CENTER);save.addActionListener(e->save());del.addActionListener(e->delete());clear.addActionListener(e->{t.clearSelection();nombre.setText("");});refresh.addActionListener(e->load());t.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&t.getSelectedRow()>=0)nombre.setText(String.valueOf(t.getValueAt(t.convertRowIndexToModel(t.getSelectedRow()),1)));});load();}
 private int id(){int r=t.getSelectedRow();return r<0?-1:Integer.parseInt(m.getValueAt(t.convertRowIndexToModel(r),0).toString());}
 private void save(){if(!UiSupport.required(nombre.getText())){JOptionPane.showMessageDialog(this,"Ingresa el nombre del repartidor.");return;}try{if(id()<0){dao.create(new Repartidor(nombre.getText().trim()));JOptionPane.showMessageDialog(this,"Repartidor registrado.");}else{dao.update(id(),new Repartidor(nombre.getText().trim()));JOptionPane.showMessageDialog(this,"Repartidor actualizado.");}nombre.setText("");t.clearSelection();load();}catch(Exception e){UiSupport.error(this,e);}}
 private void delete(){if(id()<0){JOptionPane.showMessageDialog(this,"Selecciona un repartidor.");return;}if(JOptionPane.showConfirmDialog(this,"¿Eliminar repartidor seleccionado?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{dao.delete(id());JOptionPane.showMessageDialog(this,"Repartidor eliminado.");load();}catch(Exception e){UiSupport.error(this,e);}}
 private void load(){try{m.setRowCount(0);for(Repartidor x:dao.readAll())m.addRow(new Object[]{x.getId(),x.getNombre()});}catch(Exception e){UiSupport.error(this,e);}}
}
